In [1]:
import graphlab as gl
import numpy
from matplotlib import pyplot as plt
%matplotlib inline

This non-commercial license of GraphLab Create for academic use is assigned to minggong@thoughtworks.com and will expire on July 06, 2017.

[INFO] graphlab.cython.cy_server: GraphLab Create v2.1 started. Logging: /tmp/graphlab_server_1472849802.log

In [2]:
sales = gl.SFrame('../week1-simple-regression/kc_house_data.gl/')

In [5]:
sales.sort(['sqft_living', 'price'])

Columns:
	id	str
	date	datetime
	price	float
	bedrooms	float
	bathrooms	float
	sqft_living	float
	sqft_lot	int
	floors	str
	waterfront	int
	view	int
	condition	int
	grade	int
	sqft_above	int
	sqft_basement	int
	yr_built	int
	yr_renovated	int
	zipcode	str
	lat	float
	long	float
	sqft_living15	float
	sqft_lot15	float

Rows: 21613

Data:
+------------+---------------------------+----------+----------+-----------+
|     id     |            date           |  price   | bedrooms | bathrooms |
+------------+---------------------------+----------+----------+-----------+
| 3980300371 | 2014-09-26 00:00:00+00:00 | 142000.0 |   0.0    |    0.0    |
| 2856101479 | 2014-07-01 00:00:00+00:00 | 276000.0 |   1.0    |    0.75   |
| 1723049033 | 2014-06-20 00:00:00+00:00 | 245000.0 |   1.0    |    0.75   |
| 1222029077 | 2014-10-29 00:00:00+00:00 | 265000.0 |   0.0    |    0.75   |
| 6896300380 | 2014-10-02 00:00:00+00:00 | 228000.0 |   0.0    |    1.0    |
| 9266700190 | 2015-05-11 00:00:00+00:00 | 245000.0 |   1.0    |    1.0    |
| 6303400395 | 2015-01-30 00:00:00+00:00 | 325000.0 |   1.0    |    0.75   |
| 4322200105 | 2015-03-31 00:00:00+00:00 | 229050.0 |   1.0    |    1.0    |
| 7549801385 | 2014-06-12 00:00:00+00:00 | 280000.0 |   1.0    |    0.75   |
| 8658300340 | 2014-05-23 00:00:00+00:00 | 80000.0  |   1.0    |    0.75   |
+------------+---------------------------+----------+----------+-----------+
+-------------+----------+--------+------------+------+-----------+-------+------------+
| sqft_living | sqft_lot | floors | waterfront | view | condition | grade | sqft_above |
+-------------+----------+--------+------------+------+-----------+-------+------------+
|    290.0    |  20875   |   1    |     0      |  0   |     1     |   1   |    290     |
|    370.0    |   1801   |   1    |     0      |  0   |     5     |   5   |    370     |
|    380.0    |  15000   |   1    |     0      |  0   |     3     |   5   |    380     |
|    384.0    |  213444  |   1    |     0      |  0   |     3     |   4   |    384     |
|    390.0    |   5900   |   1    |     0      |  0   |     2     |   4   |    390     |
|    390.0    |   2000   |   1    |     0      |  0   |     4     |   6   |    390     |
|    410.0    |   8636   |   1    |     0      |  0   |     2     |   4   |    410     |
|    420.0    |   3298   |   1    |     0      |  0   |     4     |   4   |    420     |
|    420.0    |   6720   |   1    |     0      |  0   |     3     |   5   |    420     |
|    430.0    |   5050   |   1    |     0      |  0   |     2     |   4   |    430     |
+-------------+----------+--------+------------+------+-----------+-------+------------+
+---------------+----------+--------------+---------+-------------+
| sqft_basement | yr_built | yr_renovated | zipcode |     lat     |
+---------------+----------+--------------+---------+-------------+
|       0       |   1963   |      0       |  98024  | 47.53077245 |
|       0       |   1923   |      0       |  98117  | 47.67782145 |
|       0       |   1963   |      0       |  98168  | 47.48103428 |
|       0       |   2003   |      0       |  98070  | 47.41772688 |
|       0       |   1953   |      0       |  98118  | 47.52604001 |
|       0       |   1920   |      0       |  98103  | 47.69377314 |
|       0       |   1953   |      0       |  98146  |  47.5076723 |
|       0       |   1949   |      0       |  98136  |  47.5374761 |
|       0       |   1922   |      0       |  98108  | 47.55198122 |
|       0       |   1912   |      0       |  98014  | 47.64994341 |
+---------------+----------+--------------+---------+-------------+
+---------------+---------------+-----+
|      long     | sqft_living15 | ... |
+---------------+---------------+-----+
| -121.88842327 |     1620.0    | ... |
| -122.38911208 |     1340.0    | ... |
|  -122.322601  |     1170.0    | ... |
| -122.49121696 |     1920.0    | ... |
| -122.26142752 |     2170.0    | ... |
| -122.34662226 |     1340.0    | ... |
| -122.35672193 |     1190.0    | ... |
|  -122.391385  |     1460.0    | ... |
| -122.31082137 |     1420.0    | ... |
| -121.90868353 |     1200.0    | ... |
+---------------+---------------+-----+
[21613 rows x 21 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.

In [19]:
def polynomial_sframe(feature, degree):
    poly_sframe = gl.SFrame()
    poly_sframe['power_1'] = feature
    if degree > 1:
        for power in range(2, degree+1): 
            # first we'll give the column a name:
            name = 'power_' + str(power)
            # then assign poly_sframe[name] to the appropriate power of feature
            poly_sframe[name] = gl.SArray(feature).apply(lambda x: x**power)
    return poly_sframe

def polynomial_model(feature, degree, penalty):
    poly_data = polynomial_sframe(sales[feature], degree)
    my_features = poly_data.column_name()
    poly_data['price'] = sales['price']
    model = gl.linear_regression.create(poly_data, features=my_features, target='price', l2_penalty=penalty, validation_set=None,verbose=False)
    return model

In [16]:
model = polynomial_model(sales['sqft_living'], 15)

In [18]:
my_features = poly2_data.column_names() # get the name of the features
poly2_data['price'] = sales['price'] # add price to the data since it's the target

model = gl.linear_regression.create(poly15_data, target='price', l2_penalty=1.5e-5, validation_set=None,verbose=False)

ToolkitError: The following columns were expected but are missing: ['price']